
import './assets/Accountants/css/reg.css'
import { Link } from 'react-router-dom';
import React, { Component } from 'react';
import axios from 'axios';
import swal from 'sweetalert';
import jsPDF from 'jspdf';
import logo from './images/arm-logo.jpeg';
import user from './images/user.png';
import Sidebar from './layouts/accountant/sidebar';
class PaySheetRequest extends Component {

    state = {
        reqid: '',
        ename: '',
        nic: '',
        basic: '',
        ot: '',
        epf: '',
        etf: '',
        time: '',
        bonuse: '',

        channelcharges: '',
        total: '',
        padate: '',
    }
    validateNIC = (e) =>{
        var nic = document.getElementById('nic');
        var msg = document.getElementById('msg');
    
        if (nic.value.length == 10) {
          
            msg.innerHTML = "N.I.C. length is valid";
            msg.style.color = "#350D7C";
        } else if(nic.value.length == 12){
            msg.innerHTML = "N.I.C. length is valid";
            msg.style.color = "#350D7C";
        }else{
            msg.innerHTML = "N.I.C. must be 10 or 12 characters";
            msg.style.color = "#F10707";
        }
    }
    handleInput = (e) => {
        this.setState({

            [e.target.name]: e.target.value
        });

    }
    //  pdfGenerate(){

    //     var doc = new jsPDF('portaite','px','a4','false');
        
    //     doc.addImage(logo,'jpeg',80,20,200,300);
    //     // doc.addPage()
    //     doc.setFont('Cursive','bold');
    //     doc.setFillColor('blue');
    //     doc.setTextColor('Blue');
    //     doc.setFontSize('40');
    //     doc.text(100,60,'Armadal Hospital');
        
    //     doc.setFont('Cursive','normal');
    //     doc.setTextColor('#cc0099');
    //     doc.setFontSize('30');
    //     doc.text(100,210,'Finance Department');

    //     doc.setFont('Cursive','italic');
    //     doc.setTextColor('Black');
    //     doc.setFontSize('25');
    //     doc.text(20,120,'This is a valid pdf document generated by Armadal hospital finance departmenet');
    //     doc.setLineWidth(10.0); 
    //     doc.line(30, 230, 560, 30); // horizontal line  

        

    //     doc.addImage(user,'png',110,100,50,80);
    //     doc.setFont('Cursive','italic');
    //     doc.setTextColor('#000033');
    //     doc.setFontSize('15');
    //     doc.text(200,240,'Armadal Hospital pvt(ltd)');
    //     doc.text(200,245,'Finance Department');
    //     doc.text(200,250,'Kawdana Road,Dehiwala');
    //     doc.text(200,255,'Hotline:011 477 577');
    //     //getting added values
    //     var reqID= document.getElementById("reqID").value;
    //     var empName= document.getElementById("name").value;
    //     var NIC= document.getElementById("nic").value;
    //     var basic= document.getElementById("basicSal").value;
    //     var OT= document.getElementById("ot").value;
    //     var epf= document.getElementById("epf").value;
    //     var etf= document.getElementById("etf").value;
    //     var time= document.getElementById("time").value;
    //     var bonus= document.getElementById("bonus").value;
    //     var channel= document.getElementById("channel").value;
    //     var total= document.getElementById("total").value;

        


    //     doc.addPage();
    //     doc.setFont('Cursive','normal');
    //     doc.setTextColor('black');
    //     doc.setFontSize('20');
    //     doc.text(100,50,'Your monthly paysheet of');
    //     doc.text(200,50,time);
    //     doc.text(100,60,'Your pay sheet request ID');
    //     doc.text(100,65,'Employee name');
    //     doc.text(100,70,'Employee nic number');
    //     doc.text(100,85,'Salary has calculated as bellow');
    //     doc.text(reqID,100,60);
    //     doc.text(empName,100,65);
    //     doc.text(NIC,100,70);
    //     doc.line(30, 30, 560, 30); // horizontal line  

    //      doc.setLineWidth(300);  
       
    //     doc.text(100,95,'Basic Salary');
    //     doc.text(100,80,'Over Time');
    //     doc.text(100,85,'EPF');
    //     doc.text(basic,100,100);
    //     doc.text(OT,100,120);
    //     doc.text(epf,100,100);
        
        
        
        
        
        
    //     doc.save('paysheet.pdf')
    // }
    async componentDidMount() {


        const req_id = this.props.match.params.id;
        const e_nic = this.props.match.params.nic;
        console.log(req_id);
        console.log(e_nic);

        document.getElementById('rrt').innerText = req_id;
        document.getElementById('empnic').innerText = e_nic;
        



    }

    addPaysheet = async (e) => {

        e.preventDefault();
        const res = await axios.post('http://localhost:8000/api/addPaySheet', this.state);
        if (res.data.status === 200) {
            //console.log(res.data.message);
            swal({
                title: "Success!",
                text: res.data.message,
                icon: "success",
                button: "ok!",
            });
            this.setState({
                reqid: '',
                ename:'',
                nic: '',
                basic: '',
                ot: '',
                epf: '',
                etf: '',
                time: '',
                bonuse: '',

                channelcharges: '',
                total: '',
                padate: '',

            });
        }

    }

    render() {
        return (
            
            <div className="container"> 
            <Sidebar />
            
                                <h1 className="h1"> Add the pay sheet</h1>
                                <br/>
                                <div className="drt">
                                <div className="mmm">The pay sheet request id of this paysheet request:
                                           
                                        <div id="rrt" ><h1>******** </h1></div>
                                        <div id="empnic" ><h1>******** </h1></div>
                                        </div>
                                        <br/>
                                        </div>
                                <form onSubmit={this.addPaysheet}>

                          <table >
                            <thead>
                              <tr>
                                 <th>
                                    <div className="addOne">
                                            
         
                                            <label className="labelsreg1">Employee's request Id :</label>
                                            <input type="text" id="reqID" name="reqid" onChange={this.handleInput} value={this.state.reqid} className="form-control " placeholder="request id" />

                                            <label className="labelsreg1">Employee's full name :</label>
                                            <input type="text" id="name" name="ename" onChange={this.handleInput} value={this.state.ename} className="form-control " placeholder="full name" />
                                             
                                            <label className="labelsreg1">Employees' NIC number :</label>
                                            <input type="text" id="nic" onKeyUp={this.validateNIC} name="nic" onChange={this.handleInput} value={this.state.nic} className="form-control " placeholder="NICnumber" />
                                            <span id="msg"></span> 
                                            {/* <input type="text" name="select" onChange={this.handleInput} value={this.state.select} className="form-control" aria-label=".form-select-sm example"/> */}
                                            {/* <option selected>Select</option>
                                                <option value="1">Nurses</option>
                                                <option value="2">Doctors</option>
                                                <option value="3">Radiologists</option>
                                                <option value="4">Accountants</option>
                                                <option value="5">Pharmasists</option>
                                                <option value="6">Ambulance Staff</option> */}

                                            <div className="form-group mb-3">
                                                <label className="labelsreg1">basic Salary  :</label>
                                                <input type="text" name="basic" id="basicSal" onChange={this.handleInput} value={this.state.basic} className="form-control" placeholder="perment or trainng" />
                                            </div>

                                            <label className="labelsreg1">OT payments :</label>
                                            <input type="text" name="ot" id="ot" onChange={this.handleInput} value={this.state.ot} className="form-control" placeholder="nic" />

                                            <p className="labelsreg1">should be deducted</p>

                                            <label className="labelsreg1"> EPF:</label>
                                            <input type="text" name="epf" id="epf" onChange={this.handleInput} value={this.state.epf} className="form-control" placeholder="eid" />

                                            <label className="labelsreg1">ETF :</label>
                                            <input type="text" name="etf" id="etf" onChange={this.handleInput} value={this.state.etf} className="form-control" placeholder="OT hrs" />
                                       </div>
                                       </th>
                                       <th>
                                       <div className="addtwo">
                                            
                                            <p className="labelsreg1">The time period</p>

                                            <label className="labelsreg1">The month and year  :</label>
                                            <input type="text" id="time" name="time" onChange={this.handleInput} value={this.state.time} className="form-control" placeholder="month and year" />

                                            <p className="labelsreg1">Should be add</p>

                                            <label className="labelsreg1"> Sesonal bonuses :</label>
                                            <input type="text" id="bonus"name="bonuse" onChange={this.handleInput} value={this.state.bonuse} className="form-control" placeholder="month and year" />

                                            <p className="labelsreg1">Only applicable if employee is a doctor</p>

                                            <label className="labelsreg1"> total channeling fee charges:</label>
                                            <input type="text" id="channel" name="channelcharges" onChange={this.handleInput} value={this.state.channelcharges} className="form-control" placeholder="eid" />

                                            <label className="labelsreg1"> total salary:</label>
                                            <input type="text" id="total" name="total" onChange={this.handleInput} value={this.state.total} className="form-control" placeholder="eid" />




                                            <label className="labelsreg1">The date pay sheet made   :</label>
                                            <input type="date" name="padate" onChange={this.handleInput} value={this.state.padate} className="form-control" placeholder="confirm the password" />
                                            {/* <button  className="buttonr3" onClick={this.pdfGenerate}>Generate The pay sheet</button> */}
                                            <button type="submit" className="buttonr3">Make The pay sheet</button>
                                      </div>
                                </th>
                            </tr>
                        </thead>
                    </table>
                </form>
             </div>

        );
    }
}
export default PaySheetRequest;
