import './assets/Accountants/css/reg.css'
import { Link } from 'react-router-dom';
import React, { Component, useState } from 'react';
import axios from 'axios';
import swal from 'sweetalert';
import Spinner from 'react-bootstrap/Spinner';
import Table from 'react-bootstrap/Table';
import jsPDF from 'jspdf';
import logo from './images/arm-logo.jpeg';
import ReactHTMLTableToExcel from 'react-html-table-to-excel';
import autoTable from 'jspdf-autotable'
import user from './images/user.png';
function pdfGenerate() {

    var doc = new jsPDF('landscape', 'px', 'a4', 'false');

    doc.addImage(logo, 'jpeg', 80, 20, 350, 300);
    // doc.addPage()
    doc.setFont('Cursive', 'bold');
    doc.setFillColor('blue');
    doc.setTextColor('Blue');
    doc.setFontSize('40');
    doc.text(200, 60, 'Armadal Hospital');

    doc.setFont('Cursive', 'normal');
    doc.setTextColor('#000066');
    doc.setFontSize('18');
    doc.text(200, 85, 'Your trustworthy medical supplier');
    doc.setFont('Cursive','normal');
    doc.setTextColor('#660066');
    doc.setFontSize('30');
    doc.text(400,300,'Finance Department');
    doc.addImage(user, 'jpeg', 500, 200, 70, 70);
    doc.line(15, 15, 550, 15);    
    doc.setLineWidth(3.5);   // horizontal line 
    doc.setFont('Cursive','italic');
    doc.setTextColor('Black');
    doc.setFontSize('15');
    doc.text(50,320,'This is a valid pdf document generated by Armadal hospital finance departmenet');
    doc.text(50,340,'if you have any concerns please contact us');
    doc.addPage()
   
   
    doc.autoTable({
        styles: { fillColor: [255, 0, 0] },
        columnStyles: { 0: { halign: 'center', fillColor: [0, 255, 0] } }, // Cells in first column centered and green
        margin: { top: 10 },
        body: [
            [{ content: 'This is your monthly paysheet', colSpan: 2, rowSpan: 2, styles: { halign: 'center' } }],
          ],
        })
    autoTable(doc, { html: '#serch' })
    doc.line(150, 15, 600, 20);    
    doc.setLineWidth(1.5);   // horizontal line 
    doc.setFont('Cursive','italic');
    doc.setTextColor('#000033');
    doc.setFontSize('25');
    doc.text(400,240,'Armadal Hospital pvt(ltd)');
    doc.text(400,255,'Finance Department');
    doc.text(400,270,'Kawdana Road,Dehiwala');
    doc.text(400,285,'Hotline:011 477 577');




    doc.save('paysheet.pdf')
}


function SearchPaySheet() {

    const [data, setData] = useState([])
    async function search(key) {
        console.warn(key)
        let result = await fetch('http://localhost:8000/api/search/' + key);
        result = await result.json();
        console.warn(result)
        setData(result)

    }




    return (

        <div className="container">
            <div className="col-md-6">
                <div className="jk">
                    <h1>Search Your Paysheet</h1>
                    <br />
                    <label >Please input your NIC number  :</label>
                    <input type="text" className="asd" onChange={(e) => search(e.target.value)} className="form-control" placeholder="please type your nic number"></input>

                    <form>
                    <Table id="serch"striped bordered hover variant="dark">
                            <thead>
                                <tr>
                                    <th id="reqID">Pay Sheet Requst ID </th>
                                    <th>Employee's Name  </th>
                                    <th>Employee's NIC  </th>
                                    <th>Basic Salary </th>
                                    <th>Your OT payment </th>
                                    <th>EPF </th>
                                    <th>ETF </th>
                                    <th>Month and Yer  of the paysheet </th>
                                    <th>Your Bonuses </th>
                                    <th>Channeling Charges  </th>
                                    <th>Total Salary </th>
                                    <th>The date you made the request </th>



                                </tr>
                                {
                                    data.map((item) =>



                                        <tr key={item.id}>
                                            <td > <label >{item.reqid}</label></td>
                                            <td><label id="empName">{item.ename}</label></td>
                                            <td><label id="NIC">{item.nic}</label></td>
                                            <td>{item.basic}</td>
                                            <td>{item.ot}</td>
                                            <td>{item.epf}</td>
                                            <td>{item.etf}</td>
                                            <td>{item.time}</td>
                                            <td>{item.bonuse}</td>
                                            <td>{item.channelcharges}</td>
                                            <td>{item.total}</td>
                                            <td>{item.padate}</td>


                                        </tr>
                                    )
                                }



                            </thead>

                        </Table>
                    </form>
                    <br />
                    <br />

                    <button className="btn btn-danger btn-sm"  onClick={pdfGenerate}>Generate pay Sheet</button>
                    <br />
                    <br />
                    
                    <ReactHTMLTableToExcel
                        id="serchBTn"
                        className="btn btn-info btn-sm"
                        table="serch"
                        filename="paysheetxl"
                        sheet="sheet"
                        buttonText="Download as excel sheet" />


                </div>
            </div>

        </div>

    )

}
export default SearchPaySheet;
